/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExpirationOffset;
import io.swagger.client.model.Fulfillment;
import io.swagger.client.model.UserAssociation;
import java.io.IOException;

/**
 * BulkIssuanceRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class BulkIssuanceRequest {
  @SerializedName("token")
  private String token = null;

  @SerializedName("fulfillment")
  private Fulfillment fulfillment = null;

  @SerializedName("expedite")
  private Boolean expedite = false;

  @SerializedName("card_product_token")
  private String cardProductToken = null;

  @SerializedName("card_allocation")
  private Integer cardAllocation = null;

  @SerializedName("user_association")
  private UserAssociation userAssociation = null;

  @SerializedName("name_line_1_numeric_postfix")
  private Boolean nameLine1NumericPostfix = false;

  @SerializedName("name_line_1_random_postfix")
  private Boolean nameLine1RandomPostfix = false;

  @SerializedName("expiration_offset")
  private ExpirationOffset expirationOffset = null;

  public BulkIssuanceRequest token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(required = true, value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public BulkIssuanceRequest fulfillment(Fulfillment fulfillment) {
    this.fulfillment = fulfillment;
    return this;
  }

   /**
   * Get fulfillment
   * @return fulfillment
  **/
  @ApiModelProperty(required = true, value = "")
  public Fulfillment getFulfillment() {
    return fulfillment;
  }

  public void setFulfillment(Fulfillment fulfillment) {
    this.fulfillment = fulfillment;
  }

  public BulkIssuanceRequest expedite(Boolean expedite) {
    this.expedite = expedite;
    return this;
  }

   /**
   * Get expedite
   * @return expedite
  **/
  @ApiModelProperty(value = "")
  public Boolean isExpedite() {
    return expedite;
  }

  public void setExpedite(Boolean expedite) {
    this.expedite = expedite;
  }

  public BulkIssuanceRequest cardProductToken(String cardProductToken) {
    this.cardProductToken = cardProductToken;
    return this;
  }

   /**
   * Get cardProductToken
   * @return cardProductToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCardProductToken() {
    return cardProductToken;
  }

  public void setCardProductToken(String cardProductToken) {
    this.cardProductToken = cardProductToken;
  }

  public BulkIssuanceRequest cardAllocation(Integer cardAllocation) {
    this.cardAllocation = cardAllocation;
    return this;
  }

   /**
   * Get cardAllocation
   * maximum: 50000
   * @return cardAllocation
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getCardAllocation() {
    return cardAllocation;
  }

  public void setCardAllocation(Integer cardAllocation) {
    this.cardAllocation = cardAllocation;
  }

  public BulkIssuanceRequest userAssociation(UserAssociation userAssociation) {
    this.userAssociation = userAssociation;
    return this;
  }

   /**
   * Get userAssociation
   * @return userAssociation
  **/
  @ApiModelProperty(value = "")
  public UserAssociation getUserAssociation() {
    return userAssociation;
  }

  public void setUserAssociation(UserAssociation userAssociation) {
    this.userAssociation = userAssociation;
  }

  public BulkIssuanceRequest nameLine1NumericPostfix(Boolean nameLine1NumericPostfix) {
    this.nameLine1NumericPostfix = nameLine1NumericPostfix;
    return this;
  }

   /**
   * Get nameLine1NumericPostfix
   * @return nameLine1NumericPostfix
  **/
  @ApiModelProperty(value = "")
  public Boolean isNameLine1NumericPostfix() {
    return nameLine1NumericPostfix;
  }

  public void setNameLine1NumericPostfix(Boolean nameLine1NumericPostfix) {
    this.nameLine1NumericPostfix = nameLine1NumericPostfix;
  }

  public BulkIssuanceRequest nameLine1RandomPostfix(Boolean nameLine1RandomPostfix) {
    this.nameLine1RandomPostfix = nameLine1RandomPostfix;
    return this;
  }

   /**
   * Get nameLine1RandomPostfix
   * @return nameLine1RandomPostfix
  **/
  @ApiModelProperty(value = "")
  public Boolean isNameLine1RandomPostfix() {
    return nameLine1RandomPostfix;
  }

  public void setNameLine1RandomPostfix(Boolean nameLine1RandomPostfix) {
    this.nameLine1RandomPostfix = nameLine1RandomPostfix;
  }

  public BulkIssuanceRequest expirationOffset(ExpirationOffset expirationOffset) {
    this.expirationOffset = expirationOffset;
    return this;
  }

   /**
   * Get expirationOffset
   * @return expirationOffset
  **/
  @ApiModelProperty(value = "")
  public ExpirationOffset getExpirationOffset() {
    return expirationOffset;
  }

  public void setExpirationOffset(ExpirationOffset expirationOffset) {
    this.expirationOffset = expirationOffset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkIssuanceRequest bulkIssuanceRequest = (BulkIssuanceRequest) o;
    return Objects.equals(this.token, bulkIssuanceRequest.token) &&
        Objects.equals(this.fulfillment, bulkIssuanceRequest.fulfillment) &&
        Objects.equals(this.expedite, bulkIssuanceRequest.expedite) &&
        Objects.equals(this.cardProductToken, bulkIssuanceRequest.cardProductToken) &&
        Objects.equals(this.cardAllocation, bulkIssuanceRequest.cardAllocation) &&
        Objects.equals(this.userAssociation, bulkIssuanceRequest.userAssociation) &&
        Objects.equals(this.nameLine1NumericPostfix, bulkIssuanceRequest.nameLine1NumericPostfix) &&
        Objects.equals(this.nameLine1RandomPostfix, bulkIssuanceRequest.nameLine1RandomPostfix) &&
        Objects.equals(this.expirationOffset, bulkIssuanceRequest.expirationOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, fulfillment, expedite, cardProductToken, cardAllocation, userAssociation, nameLine1NumericPostfix, nameLine1RandomPostfix, expirationOffset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkIssuanceRequest {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    fulfillment: ").append(toIndentedString(fulfillment)).append("\n");
    sb.append("    expedite: ").append(toIndentedString(expedite)).append("\n");
    sb.append("    cardProductToken: ").append(toIndentedString(cardProductToken)).append("\n");
    sb.append("    cardAllocation: ").append(toIndentedString(cardAllocation)).append("\n");
    sb.append("    userAssociation: ").append(toIndentedString(userAssociation)).append("\n");
    sb.append("    nameLine1NumericPostfix: ").append(toIndentedString(nameLine1NumericPostfix)).append("\n");
    sb.append("    nameLine1RandomPostfix: ").append(toIndentedString(nameLine1RandomPostfix)).append("\n");
    sb.append("    expirationOffset: ").append(toIndentedString(expirationOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

