/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CommandoModeEnables;
import io.swagger.client.model.RealTimeStandinCriteria;
import java.io.IOException;

/**
 * CommandoModeRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class CommandoModeRequest {
  @SerializedName("program_gateway_funding_source_token")
  private String programGatewayFundingSourceToken = null;

  @SerializedName("real_time_standin_criteria")
  private RealTimeStandinCriteria realTimeStandinCriteria = null;

  @SerializedName("commando_mode_enables")
  private CommandoModeEnables commandoModeEnables = null;

  @SerializedName("token")
  private String token = null;

  public CommandoModeRequest programGatewayFundingSourceToken(String programGatewayFundingSourceToken) {
    this.programGatewayFundingSourceToken = programGatewayFundingSourceToken;
    return this;
  }

   /**
   * Get programGatewayFundingSourceToken
   * @return programGatewayFundingSourceToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProgramGatewayFundingSourceToken() {
    return programGatewayFundingSourceToken;
  }

  public void setProgramGatewayFundingSourceToken(String programGatewayFundingSourceToken) {
    this.programGatewayFundingSourceToken = programGatewayFundingSourceToken;
  }

  public CommandoModeRequest realTimeStandinCriteria(RealTimeStandinCriteria realTimeStandinCriteria) {
    this.realTimeStandinCriteria = realTimeStandinCriteria;
    return this;
  }

   /**
   * Get realTimeStandinCriteria
   * @return realTimeStandinCriteria
  **/
  @ApiModelProperty(value = "")
  public RealTimeStandinCriteria getRealTimeStandinCriteria() {
    return realTimeStandinCriteria;
  }

  public void setRealTimeStandinCriteria(RealTimeStandinCriteria realTimeStandinCriteria) {
    this.realTimeStandinCriteria = realTimeStandinCriteria;
  }

  public CommandoModeRequest commandoModeEnables(CommandoModeEnables commandoModeEnables) {
    this.commandoModeEnables = commandoModeEnables;
    return this;
  }

   /**
   * Get commandoModeEnables
   * @return commandoModeEnables
  **/
  @ApiModelProperty(required = true, value = "")
  public CommandoModeEnables getCommandoModeEnables() {
    return commandoModeEnables;
  }

  public void setCommandoModeEnables(CommandoModeEnables commandoModeEnables) {
    this.commandoModeEnables = commandoModeEnables;
  }

  public CommandoModeRequest token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandoModeRequest commandoModeRequest = (CommandoModeRequest) o;
    return Objects.equals(this.programGatewayFundingSourceToken, commandoModeRequest.programGatewayFundingSourceToken) &&
        Objects.equals(this.realTimeStandinCriteria, commandoModeRequest.realTimeStandinCriteria) &&
        Objects.equals(this.commandoModeEnables, commandoModeRequest.commandoModeEnables) &&
        Objects.equals(this.token, commandoModeRequest.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(programGatewayFundingSourceToken, realTimeStandinCriteria, commandoModeEnables, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandoModeRequest {\n");
    
    sb.append("    programGatewayFundingSourceToken: ").append(toIndentedString(programGatewayFundingSourceToken)).append("\n");
    sb.append("    realTimeStandinCriteria: ").append(toIndentedString(realTimeStandinCriteria)).append("\n");
    sb.append("    commandoModeEnables: ").append(toIndentedString(commandoModeEnables)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

