/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DigitalWalletTokenRequestorMapUpdateModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class DigitalWalletTokenRequestorMapUpdateModel {
  @SerializedName("network")
  private String network = null;

  @SerializedName("digital_wallet_token_requestor_id")
  private String digitalWalletTokenRequestorId = null;

  @SerializedName("digital_wallet_token_requestor_name")
  private String digitalWalletTokenRequestorName = null;

  public DigitalWalletTokenRequestorMapUpdateModel network(String network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNetwork() {
    return network;
  }

  public void setNetwork(String network) {
    this.network = network;
  }

  public DigitalWalletTokenRequestorMapUpdateModel digitalWalletTokenRequestorId(String digitalWalletTokenRequestorId) {
    this.digitalWalletTokenRequestorId = digitalWalletTokenRequestorId;
    return this;
  }

   /**
   * Get digitalWalletTokenRequestorId
   * @return digitalWalletTokenRequestorId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDigitalWalletTokenRequestorId() {
    return digitalWalletTokenRequestorId;
  }

  public void setDigitalWalletTokenRequestorId(String digitalWalletTokenRequestorId) {
    this.digitalWalletTokenRequestorId = digitalWalletTokenRequestorId;
  }

  public DigitalWalletTokenRequestorMapUpdateModel digitalWalletTokenRequestorName(String digitalWalletTokenRequestorName) {
    this.digitalWalletTokenRequestorName = digitalWalletTokenRequestorName;
    return this;
  }

   /**
   * Get digitalWalletTokenRequestorName
   * @return digitalWalletTokenRequestorName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDigitalWalletTokenRequestorName() {
    return digitalWalletTokenRequestorName;
  }

  public void setDigitalWalletTokenRequestorName(String digitalWalletTokenRequestorName) {
    this.digitalWalletTokenRequestorName = digitalWalletTokenRequestorName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DigitalWalletTokenRequestorMapUpdateModel digitalWalletTokenRequestorMapUpdateModel = (DigitalWalletTokenRequestorMapUpdateModel) o;
    return Objects.equals(this.network, digitalWalletTokenRequestorMapUpdateModel.network) &&
        Objects.equals(this.digitalWalletTokenRequestorId, digitalWalletTokenRequestorMapUpdateModel.digitalWalletTokenRequestorId) &&
        Objects.equals(this.digitalWalletTokenRequestorName, digitalWalletTokenRequestorMapUpdateModel.digitalWalletTokenRequestorName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, digitalWalletTokenRequestorId, digitalWalletTokenRequestorName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DigitalWalletTokenRequestorMapUpdateModel {\n");
    
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    digitalWalletTokenRequestorId: ").append(toIndentedString(digitalWalletTokenRequestorId)).append("\n");
    sb.append("    digitalWalletTokenRequestorName: ").append(toIndentedString(digitalWalletTokenRequestorName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

