/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * FundingAccountResponseModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class FundingAccountResponseModel {
  @SerializedName("created_time")
  private OffsetDateTime createdTime = null;

  @SerializedName("last_modified_time")
  private OffsetDateTime lastModifiedTime = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("token")
  private String token = null;

  @SerializedName("account_suffix")
  private String accountSuffix = null;

  @SerializedName("account_type")
  private String accountType = null;

  @SerializedName("active")
  private Boolean active = false;

  @SerializedName("is_default_account")
  private Boolean isDefaultAccount = false;

  @SerializedName("exp_date")
  private String expDate = null;

  @SerializedName("verification_status")
  private String verificationStatus = null;

  @SerializedName("date_verified")
  private OffsetDateTime dateVerified = null;

  @SerializedName("user_token")
  private String userToken = null;

  @SerializedName("business_token")
  private String businessToken = null;

  @SerializedName("name_on_account")
  private String nameOnAccount = null;

  @SerializedName("date_sent_for_verification")
  private OffsetDateTime dateSentForVerification = null;

  @SerializedName("verification_override")
  private Boolean verificationOverride = false;

  @SerializedName("verification_notes")
  private String verificationNotes = null;

  public FundingAccountResponseModel createdTime(OffsetDateTime createdTime) {
    this.createdTime = createdTime;
    return this;
  }

   /**
   * yyyy-MM-ddTHH:mm:ssZ
   * @return createdTime
  **/
  @ApiModelProperty(required = true, value = "yyyy-MM-ddTHH:mm:ssZ")
  public OffsetDateTime getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(OffsetDateTime createdTime) {
    this.createdTime = createdTime;
  }

  public FundingAccountResponseModel lastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

   /**
   * yyyy-MM-ddTHH:mm:ssZ
   * @return lastModifiedTime
  **/
  @ApiModelProperty(required = true, value = "yyyy-MM-ddTHH:mm:ssZ")
  public OffsetDateTime getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }

  public FundingAccountResponseModel type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FundingAccountResponseModel token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public FundingAccountResponseModel accountSuffix(String accountSuffix) {
    this.accountSuffix = accountSuffix;
    return this;
  }

   /**
   * Get accountSuffix
   * @return accountSuffix
  **/
  @ApiModelProperty(value = "")
  public String getAccountSuffix() {
    return accountSuffix;
  }

  public void setAccountSuffix(String accountSuffix) {
    this.accountSuffix = accountSuffix;
  }

  public FundingAccountResponseModel accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public FundingAccountResponseModel active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public FundingAccountResponseModel isDefaultAccount(Boolean isDefaultAccount) {
    this.isDefaultAccount = isDefaultAccount;
    return this;
  }

   /**
   * Get isDefaultAccount
   * @return isDefaultAccount
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDefaultAccount() {
    return isDefaultAccount;
  }

  public void setIsDefaultAccount(Boolean isDefaultAccount) {
    this.isDefaultAccount = isDefaultAccount;
  }

  public FundingAccountResponseModel expDate(String expDate) {
    this.expDate = expDate;
    return this;
  }

   /**
   * Get expDate
   * @return expDate
  **/
  @ApiModelProperty(value = "")
  public String getExpDate() {
    return expDate;
  }

  public void setExpDate(String expDate) {
    this.expDate = expDate;
  }

  public FundingAccountResponseModel verificationStatus(String verificationStatus) {
    this.verificationStatus = verificationStatus;
    return this;
  }

   /**
   * Get verificationStatus
   * @return verificationStatus
  **/
  @ApiModelProperty(value = "")
  public String getVerificationStatus() {
    return verificationStatus;
  }

  public void setVerificationStatus(String verificationStatus) {
    this.verificationStatus = verificationStatus;
  }

  public FundingAccountResponseModel dateVerified(OffsetDateTime dateVerified) {
    this.dateVerified = dateVerified;
    return this;
  }

   /**
   * Get dateVerified
   * @return dateVerified
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDateVerified() {
    return dateVerified;
  }

  public void setDateVerified(OffsetDateTime dateVerified) {
    this.dateVerified = dateVerified;
  }

  public FundingAccountResponseModel userToken(String userToken) {
    this.userToken = userToken;
    return this;
  }

   /**
   * Get userToken
   * @return userToken
  **/
  @ApiModelProperty(value = "")
  public String getUserToken() {
    return userToken;
  }

  public void setUserToken(String userToken) {
    this.userToken = userToken;
  }

  public FundingAccountResponseModel businessToken(String businessToken) {
    this.businessToken = businessToken;
    return this;
  }

   /**
   * Get businessToken
   * @return businessToken
  **/
  @ApiModelProperty(value = "")
  public String getBusinessToken() {
    return businessToken;
  }

  public void setBusinessToken(String businessToken) {
    this.businessToken = businessToken;
  }

  public FundingAccountResponseModel nameOnAccount(String nameOnAccount) {
    this.nameOnAccount = nameOnAccount;
    return this;
  }

   /**
   * Get nameOnAccount
   * @return nameOnAccount
  **/
  @ApiModelProperty(value = "")
  public String getNameOnAccount() {
    return nameOnAccount;
  }

  public void setNameOnAccount(String nameOnAccount) {
    this.nameOnAccount = nameOnAccount;
  }

  public FundingAccountResponseModel dateSentForVerification(OffsetDateTime dateSentForVerification) {
    this.dateSentForVerification = dateSentForVerification;
    return this;
  }

   /**
   * Get dateSentForVerification
   * @return dateSentForVerification
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDateSentForVerification() {
    return dateSentForVerification;
  }

  public void setDateSentForVerification(OffsetDateTime dateSentForVerification) {
    this.dateSentForVerification = dateSentForVerification;
  }

  public FundingAccountResponseModel verificationOverride(Boolean verificationOverride) {
    this.verificationOverride = verificationOverride;
    return this;
  }

   /**
   * Get verificationOverride
   * @return verificationOverride
  **/
  @ApiModelProperty(value = "")
  public Boolean isVerificationOverride() {
    return verificationOverride;
  }

  public void setVerificationOverride(Boolean verificationOverride) {
    this.verificationOverride = verificationOverride;
  }

  public FundingAccountResponseModel verificationNotes(String verificationNotes) {
    this.verificationNotes = verificationNotes;
    return this;
  }

   /**
   * Get verificationNotes
   * @return verificationNotes
  **/
  @ApiModelProperty(value = "")
  public String getVerificationNotes() {
    return verificationNotes;
  }

  public void setVerificationNotes(String verificationNotes) {
    this.verificationNotes = verificationNotes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundingAccountResponseModel fundingAccountResponseModel = (FundingAccountResponseModel) o;
    return Objects.equals(this.createdTime, fundingAccountResponseModel.createdTime) &&
        Objects.equals(this.lastModifiedTime, fundingAccountResponseModel.lastModifiedTime) &&
        Objects.equals(this.type, fundingAccountResponseModel.type) &&
        Objects.equals(this.token, fundingAccountResponseModel.token) &&
        Objects.equals(this.accountSuffix, fundingAccountResponseModel.accountSuffix) &&
        Objects.equals(this.accountType, fundingAccountResponseModel.accountType) &&
        Objects.equals(this.active, fundingAccountResponseModel.active) &&
        Objects.equals(this.isDefaultAccount, fundingAccountResponseModel.isDefaultAccount) &&
        Objects.equals(this.expDate, fundingAccountResponseModel.expDate) &&
        Objects.equals(this.verificationStatus, fundingAccountResponseModel.verificationStatus) &&
        Objects.equals(this.dateVerified, fundingAccountResponseModel.dateVerified) &&
        Objects.equals(this.userToken, fundingAccountResponseModel.userToken) &&
        Objects.equals(this.businessToken, fundingAccountResponseModel.businessToken) &&
        Objects.equals(this.nameOnAccount, fundingAccountResponseModel.nameOnAccount) &&
        Objects.equals(this.dateSentForVerification, fundingAccountResponseModel.dateSentForVerification) &&
        Objects.equals(this.verificationOverride, fundingAccountResponseModel.verificationOverride) &&
        Objects.equals(this.verificationNotes, fundingAccountResponseModel.verificationNotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdTime, lastModifiedTime, type, token, accountSuffix, accountType, active, isDefaultAccount, expDate, verificationStatus, dateVerified, userToken, businessToken, nameOnAccount, dateSentForVerification, verificationOverride, verificationNotes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundingAccountResponseModel {\n");
    
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    accountSuffix: ").append(toIndentedString(accountSuffix)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    isDefaultAccount: ").append(toIndentedString(isDefaultAccount)).append("\n");
    sb.append("    expDate: ").append(toIndentedString(expDate)).append("\n");
    sb.append("    verificationStatus: ").append(toIndentedString(verificationStatus)).append("\n");
    sb.append("    dateVerified: ").append(toIndentedString(dateVerified)).append("\n");
    sb.append("    userToken: ").append(toIndentedString(userToken)).append("\n");
    sb.append("    businessToken: ").append(toIndentedString(businessToken)).append("\n");
    sb.append("    nameOnAccount: ").append(toIndentedString(nameOnAccount)).append("\n");
    sb.append("    dateSentForVerification: ").append(toIndentedString(dateSentForVerification)).append("\n");
    sb.append("    verificationOverride: ").append(toIndentedString(verificationOverride)).append("\n");
    sb.append("    verificationNotes: ").append(toIndentedString(verificationNotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

