/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Funding;
import io.swagger.client.model.JitFundingApi;
import io.swagger.client.model.Response;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * GpaReturns
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class GpaReturns {
  @SerializedName("token")
  private String token = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("memo")
  private String memo = null;

  @SerializedName("created_time")
  private OffsetDateTime createdTime = null;

  @SerializedName("last_modified_time")
  private OffsetDateTime lastModifiedTime = null;

  @SerializedName("transaction_token")
  private String transactionToken = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("response")
  private Response response = null;

  @SerializedName("funding")
  private Funding funding = null;

  @SerializedName("funding_source_token")
  private String fundingSourceToken = null;

  @SerializedName("funding_source_address_token")
  private String fundingSourceAddressToken = null;

  @SerializedName("jit_funding")
  private JitFundingApi jitFunding = null;

  @SerializedName("original_order_token")
  private String originalOrderToken = null;

  public GpaReturns token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(required = true, value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public GpaReturns amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public GpaReturns tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public GpaReturns memo(String memo) {
    this.memo = memo;
    return this;
  }

   /**
   * Get memo
   * @return memo
  **/
  @ApiModelProperty(value = "")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public GpaReturns createdTime(OffsetDateTime createdTime) {
    this.createdTime = createdTime;
    return this;
  }

   /**
   * yyyy-MM-ddTHH:mm:ssZ
   * @return createdTime
  **/
  @ApiModelProperty(required = true, value = "yyyy-MM-ddTHH:mm:ssZ")
  public OffsetDateTime getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(OffsetDateTime createdTime) {
    this.createdTime = createdTime;
  }

  public GpaReturns lastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

   /**
   * yyyy-MM-ddTHH:mm:ssZ
   * @return lastModifiedTime
  **/
  @ApiModelProperty(required = true, value = "yyyy-MM-ddTHH:mm:ssZ")
  public OffsetDateTime getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }

  public GpaReturns transactionToken(String transactionToken) {
    this.transactionToken = transactionToken;
    return this;
  }

   /**
   * Get transactionToken
   * @return transactionToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTransactionToken() {
    return transactionToken;
  }

  public void setTransactionToken(String transactionToken) {
    this.transactionToken = transactionToken;
  }

  public GpaReturns state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public GpaReturns response(Response response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @ApiModelProperty(required = true, value = "")
  public Response getResponse() {
    return response;
  }

  public void setResponse(Response response) {
    this.response = response;
  }

  public GpaReturns funding(Funding funding) {
    this.funding = funding;
    return this;
  }

   /**
   * Get funding
   * @return funding
  **/
  @ApiModelProperty(required = true, value = "")
  public Funding getFunding() {
    return funding;
  }

  public void setFunding(Funding funding) {
    this.funding = funding;
  }

  public GpaReturns fundingSourceToken(String fundingSourceToken) {
    this.fundingSourceToken = fundingSourceToken;
    return this;
  }

   /**
   * Get fundingSourceToken
   * @return fundingSourceToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFundingSourceToken() {
    return fundingSourceToken;
  }

  public void setFundingSourceToken(String fundingSourceToken) {
    this.fundingSourceToken = fundingSourceToken;
  }

  public GpaReturns fundingSourceAddressToken(String fundingSourceAddressToken) {
    this.fundingSourceAddressToken = fundingSourceAddressToken;
    return this;
  }

   /**
   * Get fundingSourceAddressToken
   * @return fundingSourceAddressToken
  **/
  @ApiModelProperty(value = "")
  public String getFundingSourceAddressToken() {
    return fundingSourceAddressToken;
  }

  public void setFundingSourceAddressToken(String fundingSourceAddressToken) {
    this.fundingSourceAddressToken = fundingSourceAddressToken;
  }

  public GpaReturns jitFunding(JitFundingApi jitFunding) {
    this.jitFunding = jitFunding;
    return this;
  }

   /**
   * Get jitFunding
   * @return jitFunding
  **/
  @ApiModelProperty(value = "")
  public JitFundingApi getJitFunding() {
    return jitFunding;
  }

  public void setJitFunding(JitFundingApi jitFunding) {
    this.jitFunding = jitFunding;
  }

  public GpaReturns originalOrderToken(String originalOrderToken) {
    this.originalOrderToken = originalOrderToken;
    return this;
  }

   /**
   * Get originalOrderToken
   * @return originalOrderToken
  **/
  @ApiModelProperty(value = "")
  public String getOriginalOrderToken() {
    return originalOrderToken;
  }

  public void setOriginalOrderToken(String originalOrderToken) {
    this.originalOrderToken = originalOrderToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GpaReturns gpaReturns = (GpaReturns) o;
    return Objects.equals(this.token, gpaReturns.token) &&
        Objects.equals(this.amount, gpaReturns.amount) &&
        Objects.equals(this.tags, gpaReturns.tags) &&
        Objects.equals(this.memo, gpaReturns.memo) &&
        Objects.equals(this.createdTime, gpaReturns.createdTime) &&
        Objects.equals(this.lastModifiedTime, gpaReturns.lastModifiedTime) &&
        Objects.equals(this.transactionToken, gpaReturns.transactionToken) &&
        Objects.equals(this.state, gpaReturns.state) &&
        Objects.equals(this.response, gpaReturns.response) &&
        Objects.equals(this.funding, gpaReturns.funding) &&
        Objects.equals(this.fundingSourceToken, gpaReturns.fundingSourceToken) &&
        Objects.equals(this.fundingSourceAddressToken, gpaReturns.fundingSourceAddressToken) &&
        Objects.equals(this.jitFunding, gpaReturns.jitFunding) &&
        Objects.equals(this.originalOrderToken, gpaReturns.originalOrderToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, amount, tags, memo, createdTime, lastModifiedTime, transactionToken, state, response, funding, fundingSourceToken, fundingSourceAddressToken, jitFunding, originalOrderToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GpaReturns {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("    transactionToken: ").append(toIndentedString(transactionToken)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    funding: ").append(toIndentedString(funding)).append("\n");
    sb.append("    fundingSourceToken: ").append(toIndentedString(fundingSourceToken)).append("\n");
    sb.append("    fundingSourceAddressToken: ").append(toIndentedString(fundingSourceAddressToken)).append("\n");
    sb.append("    jitFunding: ").append(toIndentedString(jitFunding)).append("\n");
    sb.append("    originalOrderToken: ").append(toIndentedString(originalOrderToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

