/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MerchantScope
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class MerchantScope {
  @SerializedName("mid")
  private String mid = null;

  @SerializedName("mcc")
  private String mcc = null;

  @SerializedName("mcc_group")
  private String mccGroup = null;

  public MerchantScope mid(String mid) {
    this.mid = mid;
    return this;
  }

   /**
   * 36 char max
   * @return mid
  **/
  @ApiModelProperty(value = "36 char max")
  public String getMid() {
    return mid;
  }

  public void setMid(String mid) {
    this.mid = mid;
  }

  public MerchantScope mcc(String mcc) {
    this.mcc = mcc;
    return this;
  }

   /**
   * 4 char max
   * @return mcc
  **/
  @ApiModelProperty(value = "4 char max")
  public String getMcc() {
    return mcc;
  }

  public void setMcc(String mcc) {
    this.mcc = mcc;
  }

  public MerchantScope mccGroup(String mccGroup) {
    this.mccGroup = mccGroup;
    return this;
  }

   /**
   * 36 char max
   * @return mccGroup
  **/
  @ApiModelProperty(value = "36 char max")
  public String getMccGroup() {
    return mccGroup;
  }

  public void setMccGroup(String mccGroup) {
    this.mccGroup = mccGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantScope merchantScope = (MerchantScope) o;
    return Objects.equals(this.mid, merchantScope.mid) &&
        Objects.equals(this.mcc, merchantScope.mcc) &&
        Objects.equals(this.mccGroup, merchantScope.mccGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mid, mcc, mccGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantScope {\n");
    
    sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    mccGroup: ").append(toIndentedString(mccGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

