/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Authentication;
import io.swagger.client.model.DepositAccount;
import io.swagger.client.model.IdentificationResponseModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * UserCardHolderResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class UserCardHolderResponse {
  @SerializedName("authentication")
  private Authentication authentication = null;

  @SerializedName("token")
  private String token = null;

  @SerializedName("active")
  private Boolean active = false;

  @SerializedName("honorific")
  private String honorific = null;

  /**
   * Gets or Sets gender
   */
  @JsonAdapter(GenderEnum.Adapter.class)
  public enum GenderEnum {
    F("F"),
    
    M("M");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GenderEnum fromValue(String text) {
      for (GenderEnum b : GenderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<GenderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GenderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GenderEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return GenderEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("gender")
  private GenderEnum gender = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("middle_name")
  private String middleName = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("zip")
  private String zip = null;

  @SerializedName("postal_code")
  private String postalCode = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("parent_token")
  private String parentToken = null;

  @SerializedName("uses_parent_account")
  private Boolean usesParentAccount = false;

  @SerializedName("ssn")
  private String ssn = null;

  @SerializedName("corporate_card_holder")
  private Boolean corporateCardHolder = false;

  @SerializedName("passport_number")
  private String passportNumber = null;

  @SerializedName("id_card_number")
  private String idCardNumber = null;

  @SerializedName("nationality")
  private String nationality = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("ip_address")
  private String ipAddress = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("created_time")
  private OffsetDateTime createdTime = null;

  @SerializedName("last_modified_time")
  private OffsetDateTime lastModifiedTime = null;

  @SerializedName("business_token")
  private String businessToken = null;

  @SerializedName("metadata")
  private Map<String, String> metadata = null;

  @SerializedName("account_holder_group_token")
  private String accountHolderGroupToken = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    UNVERIFIED("UNVERIFIED"),
    
    LIMITED("LIMITED"),
    
    ACTIVE("ACTIVE"),
    
    SUSPENDED("SUSPENDED"),
    
    CLOSED("CLOSED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("identifications")
  private List<IdentificationResponseModel> identifications = null;

  @SerializedName("deposit_account")
  private DepositAccount depositAccount = null;

  @SerializedName("birth_date")
  private String birthDate = null;

  @SerializedName("passport_expiration_date")
  private String passportExpirationDate = null;

  @SerializedName("id_card_expiration_date")
  private String idCardExpirationDate = null;

  public UserCardHolderResponse authentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Get authentication
   * @return authentication
  **/
  @ApiModelProperty(value = "")
  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }

  public UserCardHolderResponse token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public UserCardHolderResponse active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Default is true
   * @return active
  **/
  @ApiModelProperty(value = "Default is true")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public UserCardHolderResponse honorific(String honorific) {
    this.honorific = honorific;
    return this;
  }

   /**
   * Get honorific
   * @return honorific
  **/
  @ApiModelProperty(value = "")
  public String getHonorific() {
    return honorific;
  }

  public void setHonorific(String honorific) {
    this.honorific = honorific;
  }

  public UserCardHolderResponse gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public UserCardHolderResponse firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserCardHolderResponse middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @ApiModelProperty(value = "")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public UserCardHolderResponse lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserCardHolderResponse email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserCardHolderResponse address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @ApiModelProperty(value = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public UserCardHolderResponse address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @ApiModelProperty(value = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public UserCardHolderResponse city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public UserCardHolderResponse state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public UserCardHolderResponse zip(String zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  @ApiModelProperty(value = "")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public UserCardHolderResponse postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @ApiModelProperty(value = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public UserCardHolderResponse country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public UserCardHolderResponse notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public UserCardHolderResponse phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public UserCardHolderResponse parentToken(String parentToken) {
    this.parentToken = parentToken;
    return this;
  }

   /**
   * Get parentToken
   * @return parentToken
  **/
  @ApiModelProperty(value = "")
  public String getParentToken() {
    return parentToken;
  }

  public void setParentToken(String parentToken) {
    this.parentToken = parentToken;
  }

  public UserCardHolderResponse usesParentAccount(Boolean usesParentAccount) {
    this.usesParentAccount = usesParentAccount;
    return this;
  }

   /**
   * Default is false
   * @return usesParentAccount
  **/
  @ApiModelProperty(value = "Default is false")
  public Boolean isUsesParentAccount() {
    return usesParentAccount;
  }

  public void setUsesParentAccount(Boolean usesParentAccount) {
    this.usesParentAccount = usesParentAccount;
  }

  public UserCardHolderResponse ssn(String ssn) {
    this.ssn = ssn;
    return this;
  }

   /**
   * Get ssn
   * @return ssn
  **/
  @ApiModelProperty(value = "")
  public String getSsn() {
    return ssn;
  }

  public void setSsn(String ssn) {
    this.ssn = ssn;
  }

  public UserCardHolderResponse corporateCardHolder(Boolean corporateCardHolder) {
    this.corporateCardHolder = corporateCardHolder;
    return this;
  }

   /**
   * Get corporateCardHolder
   * @return corporateCardHolder
  **/
  @ApiModelProperty(value = "")
  public Boolean isCorporateCardHolder() {
    return corporateCardHolder;
  }

  public void setCorporateCardHolder(Boolean corporateCardHolder) {
    this.corporateCardHolder = corporateCardHolder;
  }

  public UserCardHolderResponse passportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
    return this;
  }

   /**
   * Get passportNumber
   * @return passportNumber
  **/
  @ApiModelProperty(value = "")
  public String getPassportNumber() {
    return passportNumber;
  }

  public void setPassportNumber(String passportNumber) {
    this.passportNumber = passportNumber;
  }

  public UserCardHolderResponse idCardNumber(String idCardNumber) {
    this.idCardNumber = idCardNumber;
    return this;
  }

   /**
   * Get idCardNumber
   * @return idCardNumber
  **/
  @ApiModelProperty(value = "")
  public String getIdCardNumber() {
    return idCardNumber;
  }

  public void setIdCardNumber(String idCardNumber) {
    this.idCardNumber = idCardNumber;
  }

  public UserCardHolderResponse nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  @ApiModelProperty(value = "")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public UserCardHolderResponse company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public UserCardHolderResponse ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @ApiModelProperty(value = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public UserCardHolderResponse password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserCardHolderResponse createdTime(OffsetDateTime createdTime) {
    this.createdTime = createdTime;
    return this;
  }

   /**
   * yyyy-MM-ddTHH:mm:ssZ
   * @return createdTime
  **/
  @ApiModelProperty(required = true, value = "yyyy-MM-ddTHH:mm:ssZ")
  public OffsetDateTime getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(OffsetDateTime createdTime) {
    this.createdTime = createdTime;
  }

  public UserCardHolderResponse lastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

   /**
   * yyyy-MM-ddTHH:mm:ssZ
   * @return lastModifiedTime
  **/
  @ApiModelProperty(required = true, value = "yyyy-MM-ddTHH:mm:ssZ")
  public OffsetDateTime getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }

  public UserCardHolderResponse businessToken(String businessToken) {
    this.businessToken = businessToken;
    return this;
  }

   /**
   * Get businessToken
   * @return businessToken
  **/
  @ApiModelProperty(value = "")
  public String getBusinessToken() {
    return businessToken;
  }

  public void setBusinessToken(String businessToken) {
    this.businessToken = businessToken;
  }

  public UserCardHolderResponse metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public UserCardHolderResponse putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<String, String>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public UserCardHolderResponse accountHolderGroupToken(String accountHolderGroupToken) {
    this.accountHolderGroupToken = accountHolderGroupToken;
    return this;
  }

   /**
   * Get accountHolderGroupToken
   * @return accountHolderGroupToken
  **/
  @ApiModelProperty(value = "")
  public String getAccountHolderGroupToken() {
    return accountHolderGroupToken;
  }

  public void setAccountHolderGroupToken(String accountHolderGroupToken) {
    this.accountHolderGroupToken = accountHolderGroupToken;
  }

  public UserCardHolderResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public UserCardHolderResponse identifications(List<IdentificationResponseModel> identifications) {
    this.identifications = identifications;
    return this;
  }

  public UserCardHolderResponse addIdentificationsItem(IdentificationResponseModel identificationsItem) {
    if (this.identifications == null) {
      this.identifications = new ArrayList<IdentificationResponseModel>();
    }
    this.identifications.add(identificationsItem);
    return this;
  }

   /**
   * Get identifications
   * @return identifications
  **/
  @ApiModelProperty(value = "")
  public List<IdentificationResponseModel> getIdentifications() {
    return identifications;
  }

  public void setIdentifications(List<IdentificationResponseModel> identifications) {
    this.identifications = identifications;
  }

  public UserCardHolderResponse depositAccount(DepositAccount depositAccount) {
    this.depositAccount = depositAccount;
    return this;
  }

   /**
   * Get depositAccount
   * @return depositAccount
  **/
  @ApiModelProperty(value = "")
  public DepositAccount getDepositAccount() {
    return depositAccount;
  }

  public void setDepositAccount(DepositAccount depositAccount) {
    this.depositAccount = depositAccount;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/
  @ApiModelProperty(value = "")
  public String getBirthDate() {
    return birthDate;
  }

   /**
   * Get passportExpirationDate
   * @return passportExpirationDate
  **/
  @ApiModelProperty(value = "")
  public String getPassportExpirationDate() {
    return passportExpirationDate;
  }

   /**
   * Get idCardExpirationDate
   * @return idCardExpirationDate
  **/
  @ApiModelProperty(value = "")
  public String getIdCardExpirationDate() {
    return idCardExpirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCardHolderResponse userCardHolderResponse = (UserCardHolderResponse) o;
    return Objects.equals(this.authentication, userCardHolderResponse.authentication) &&
        Objects.equals(this.token, userCardHolderResponse.token) &&
        Objects.equals(this.active, userCardHolderResponse.active) &&
        Objects.equals(this.honorific, userCardHolderResponse.honorific) &&
        Objects.equals(this.gender, userCardHolderResponse.gender) &&
        Objects.equals(this.firstName, userCardHolderResponse.firstName) &&
        Objects.equals(this.middleName, userCardHolderResponse.middleName) &&
        Objects.equals(this.lastName, userCardHolderResponse.lastName) &&
        Objects.equals(this.email, userCardHolderResponse.email) &&
        Objects.equals(this.address1, userCardHolderResponse.address1) &&
        Objects.equals(this.address2, userCardHolderResponse.address2) &&
        Objects.equals(this.city, userCardHolderResponse.city) &&
        Objects.equals(this.state, userCardHolderResponse.state) &&
        Objects.equals(this.zip, userCardHolderResponse.zip) &&
        Objects.equals(this.postalCode, userCardHolderResponse.postalCode) &&
        Objects.equals(this.country, userCardHolderResponse.country) &&
        Objects.equals(this.notes, userCardHolderResponse.notes) &&
        Objects.equals(this.phone, userCardHolderResponse.phone) &&
        Objects.equals(this.parentToken, userCardHolderResponse.parentToken) &&
        Objects.equals(this.usesParentAccount, userCardHolderResponse.usesParentAccount) &&
        Objects.equals(this.ssn, userCardHolderResponse.ssn) &&
        Objects.equals(this.corporateCardHolder, userCardHolderResponse.corporateCardHolder) &&
        Objects.equals(this.passportNumber, userCardHolderResponse.passportNumber) &&
        Objects.equals(this.idCardNumber, userCardHolderResponse.idCardNumber) &&
        Objects.equals(this.nationality, userCardHolderResponse.nationality) &&
        Objects.equals(this.company, userCardHolderResponse.company) &&
        Objects.equals(this.ipAddress, userCardHolderResponse.ipAddress) &&
        Objects.equals(this.password, userCardHolderResponse.password) &&
        Objects.equals(this.createdTime, userCardHolderResponse.createdTime) &&
        Objects.equals(this.lastModifiedTime, userCardHolderResponse.lastModifiedTime) &&
        Objects.equals(this.businessToken, userCardHolderResponse.businessToken) &&
        Objects.equals(this.metadata, userCardHolderResponse.metadata) &&
        Objects.equals(this.accountHolderGroupToken, userCardHolderResponse.accountHolderGroupToken) &&
        Objects.equals(this.status, userCardHolderResponse.status) &&
        Objects.equals(this.identifications, userCardHolderResponse.identifications) &&
        Objects.equals(this.depositAccount, userCardHolderResponse.depositAccount) &&
        Objects.equals(this.birthDate, userCardHolderResponse.birthDate) &&
        Objects.equals(this.passportExpirationDate, userCardHolderResponse.passportExpirationDate) &&
        Objects.equals(this.idCardExpirationDate, userCardHolderResponse.idCardExpirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authentication, token, active, honorific, gender, firstName, middleName, lastName, email, address1, address2, city, state, zip, postalCode, country, notes, phone, parentToken, usesParentAccount, ssn, corporateCardHolder, passportNumber, idCardNumber, nationality, company, ipAddress, password, createdTime, lastModifiedTime, businessToken, metadata, accountHolderGroupToken, status, identifications, depositAccount, birthDate, passportExpirationDate, idCardExpirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCardHolderResponse {\n");
    
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    honorific: ").append(toIndentedString(honorific)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    parentToken: ").append(toIndentedString(parentToken)).append("\n");
    sb.append("    usesParentAccount: ").append(toIndentedString(usesParentAccount)).append("\n");
    sb.append("    ssn: ").append(toIndentedString(ssn)).append("\n");
    sb.append("    corporateCardHolder: ").append(toIndentedString(corporateCardHolder)).append("\n");
    sb.append("    passportNumber: ").append(toIndentedString(passportNumber)).append("\n");
    sb.append("    idCardNumber: ").append(toIndentedString(idCardNumber)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("    businessToken: ").append(toIndentedString(businessToken)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    accountHolderGroupToken: ").append(toIndentedString(accountHolderGroupToken)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    identifications: ").append(toIndentedString(identifications)).append("\n");
    sb.append("    depositAccount: ").append(toIndentedString(depositAccount)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    passportExpirationDate: ").append(toIndentedString(passportExpirationDate)).append("\n");
    sb.append("    idCardExpirationDate: ").append(toIndentedString(idCardExpirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

