/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * WebhookUpdateCustomHeaderRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-07T21:08:00.979Z")
public class WebhookUpdateCustomHeaderRequest {
  @SerializedName("custom_header")
  private Map<String, String> customHeader = null;

  public WebhookUpdateCustomHeaderRequest customHeader(Map<String, String> customHeader) {
    this.customHeader = customHeader;
    return this;
  }

  public WebhookUpdateCustomHeaderRequest putCustomHeaderItem(String key, String customHeaderItem) {
    if (this.customHeader == null) {
      this.customHeader = new HashMap<String, String>();
    }
    this.customHeader.put(key, customHeaderItem);
    return this;
  }

   /**
   * Custom headers to be passed along with request
   * @return customHeader
  **/
  @ApiModelProperty(value = "Custom headers to be passed along with request")
  public Map<String, String> getCustomHeader() {
    return customHeader;
  }

  public void setCustomHeader(Map<String, String> customHeader) {
    this.customHeader = customHeader;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookUpdateCustomHeaderRequest webhookUpdateCustomHeaderRequest = (WebhookUpdateCustomHeaderRequest) o;
    return Objects.equals(this.customHeader, webhookUpdateCustomHeaderRequest.customHeader);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customHeader);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookUpdateCustomHeaderRequest {\n");
    
    sb.append("    customHeader: ").append(toIndentedString(customHeader)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

