/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AutoReloadListResponse;
import io.swagger.client.model.AutoReloadModel;
import io.swagger.client.model.AutoReloadResponseModel;
import io.swagger.client.model.AutoReloadUpdateModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutoReloadsApi
 */
@Ignore
public class AutoReloadsApiTest {

    private final AutoReloadsApi api = new AutoReloadsApi();

    
    /**
     * Lists all auto reloads for the program
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAutoreloadsTest() throws ApiException {
        String cardProduct = null;
        String userToken = null;
        String businessToken = null;
        Integer count = null;
        Integer startIndex = null;
        String fields = null;
        String sortBy = null;
        AutoReloadListResponse response = api.getAutoreloads(cardProduct, userToken, businessToken, count, startIndex, fields, sortBy);

        // TODO: test validations
    }
    
    /**
     * Returns a specific auto reload object
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAutoreloadsTokenTest() throws ApiException {
        String token = null;
        String fields = null;
        AutoReloadResponseModel response = api.getAutoreloadsToken(token, fields);

        // TODO: test validations
    }
    
    /**
     * Creates an auto reload object
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postAutoreloadsTest() throws ApiException {
        AutoReloadModel body = null;
        AutoReloadResponseModel response = api.postAutoreloads(body);

        // TODO: test validations
    }
    
    /**
     * Updates a specific auto reload object
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putAutoreloadsTokenTest() throws ApiException {
        AutoReloadUpdateModel body = null;
        String token = null;
        AutoReloadResponseModel response = api.putAutoreloadsToken(body, token);

        // TODO: test validations
    }
    
}
