/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CommandoModeListResponse;
import io.swagger.client.model.CommandoModeResponse;
import io.swagger.client.model.CommandoModeTransitionListResponse;
import io.swagger.client.model.CommandoModeTransitionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommandoModesApi
 */
@Ignore
public class CommandoModesApiTest {

    private final CommandoModesApi api = new CommandoModesApi();

    
    /**
     * Lists all commando mode control sets
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommandomodesTest() throws ApiException {
        Integer count = null;
        Integer startIndex = null;
        String sortBy = null;
        CommandoModeListResponse response = api.getCommandomodes(count, startIndex, sortBy);

        // TODO: test validations
    }
    
    /**
     * Lists all commando mode transitions related to a commando mode control set
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommandomodesCommandomodetokenTransitionsTest() throws ApiException {
        String commandomodeToken = null;
        Integer count = null;
        Integer startIndex = null;
        String sortBy = null;
        CommandoModeTransitionListResponse response = api.getCommandomodesCommandomodetokenTransitions(commandomodeToken, count, startIndex, sortBy);

        // TODO: test validations
    }
    
    /**
     * Returns a specific commando mode control set
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommandomodesTokenTest() throws ApiException {
        String token = null;
        CommandoModeResponse response = api.getCommandomodesToken(token);

        // TODO: test validations
    }
    
    /**
     * Returns a specific commando mode transition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommandomodesTransitionsTokenTest() throws ApiException {
        String token = null;
        CommandoModeTransitionResponse response = api.getCommandomodesTransitionsToken(token);

        // TODO: test validations
    }
    
}
